name:                ryu
version:             0.1.0.0
github:              "Lumaere/ryu"
license:             BSD3
author:              "Lawrence Wu"
maintainer:          "lawrencejwu@gmail.com"
copyright:           "2020 Lawrence Wu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Lumaere/ryu#readme>

dependencies:
- base >= 4.7 && < 5
- array
- floating-bits
- lens

library:
  source-dirs: src

executables:
  ryu-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ryu

tests:
  ryu-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ryu
    - hspec
    - QuickCheck
